#!/usr/bin/env bash
# Used to update the private dev flake hash reference.
set -euo pipefail

cd "$(dirname "$0")"

echo "Updating $PWD/private.narHash" >&2

nix --extra-experimental-features 'flakes nix-command' flake lock ./private
nix --extra-experimental-features 'flakes nix-command' hash path ./private >./private.narHash

echo OK
