name: Nix
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: nscloud-ubuntu-22.04-arm64-4x32
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: ./dev/ci.sh
